//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.Framework.DbAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbFrameworkContext : DbContext
    {
        public DbFrameworkContext()
            : base("name=DbFrameworkContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_QWF_Config> T_QWF_Config { get; set; }
        public DbSet<T_QWF_LoginLog> T_QWF_LoginLog { get; set; }
        public DbSet<T_QWF_Menu> T_QWF_Menu { get; set; }
        public DbSet<T_QWF_MenuInUrl> T_QWF_MenuInUrl { get; set; }
        public DbSet<T_QWF_Org> T_QWF_Org { get; set; }
        public DbSet<T_QWF_Resource> T_QWF_Resource { get; set; }
        public DbSet<T_QWF_Role> T_QWF_Role { get; set; }
        public DbSet<T_QWF_RoleGroup> T_QWF_RoleGroup { get; set; }
        public DbSet<T_QWF_RoleInMenu> T_QWF_RoleInMenu { get; set; }
        public DbSet<T_QWF_RoleInResource> T_QWF_RoleInResource { get; set; }
        public DbSet<T_QWF_Seq> T_QWF_Seq { get; set; }
        public DbSet<T_QWF_User> T_QWF_User { get; set; }
        public DbSet<T_QWF_UserActionLog> T_QWF_UserActionLog { get; set; }
        public DbSet<T_QWF_UserInRole> T_QWF_UserInRole { get; set; }
    }
}
