//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.Framework.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QWF_RoleGroup
    {
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string GroupRemarks { get; set; }
        public int SortId { get; set; }
        public int IsDelete { get; set; }
    }
}
