//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanyunLanyunMES.UI.Report {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Report.IReport")]
    public interface IReport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport/GetCard", ReplyAction="http://tempuri.org/IReport/GetCardResponse")]
        MES.Server.Model.Card GetCard(string cardNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport/OperationStart", ReplyAction="http://tempuri.org/IReport/OperationStartResponse")]
        void OperationStart(MES.Server.Model.CardMain[] cards);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport/ReportOP", ReplyAction="http://tempuri.org/IReport/ReportOPResponse")]
        string ReportOP(MES.Server.Model.CardDetail detail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport/GetOperationList", ReplyAction="http://tempuri.org/IReport/GetOperationListResponse")]
        MES.Server.Model.Operation[] GetOperationList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport/GetPersonList", ReplyAction="http://tempuri.org/IReport/GetPersonListResponse")]
        MES.Server.Model.Person[] GetPersonList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport/ReportCanel", ReplyAction="http://tempuri.org/IReport/ReportCanelResponse")]
        void ReportCanel(string cardNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport/SplitCard", ReplyAction="http://tempuri.org/IReport/SplitCardResponse")]
        string SplitCard(string cardNo, decimal splitQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReport/GetVersion", ReplyAction="http://tempuri.org/IReport/GetVersionResponse")]
        MES.Server.Model.MESVerion GetVersion(string cType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportChannel : LanyunLanyunMES.UI.Report.IReport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportClient : System.ServiceModel.ClientBase<LanyunLanyunMES.UI.Report.IReport>, LanyunLanyunMES.UI.Report.IReport {
        
        public ReportClient() {
        }
        
        public ReportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MES.Server.Model.Card GetCard(string cardNo) {
            return base.Channel.GetCard(cardNo);
        }
        
        public void OperationStart(MES.Server.Model.CardMain[] cards) {
            base.Channel.OperationStart(cards);
        }
        
        public string ReportOP(MES.Server.Model.CardDetail detail) {
            return base.Channel.ReportOP(detail);
        }
        
        public MES.Server.Model.Operation[] GetOperationList() {
            return base.Channel.GetOperationList();
        }
        
        public MES.Server.Model.Person[] GetPersonList() {
            return base.Channel.GetPersonList();
        }
        
        public void ReportCanel(string cardNo) {
            base.Channel.ReportCanel(cardNo);
        }
        
        public string SplitCard(string cardNo, decimal splitQty) {
            return base.Channel.SplitCard(cardNo, splitQty);
        }
        
        public MES.Server.Model.MESVerion GetVersion(string cType) {
            return base.Channel.GetVersion(cType);
        }
    }
}
