//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCRMContext : DbContext
    {
        public DbCRMContext()
            : base("name=DbCRMContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_QCRM_CustomerProduct> T_QCRM_CustomerProduct { get; set; }
        public DbSet<T_QCRM_ListInForm> T_QCRM_ListInForm { get; set; }
        public DbSet<T_QCRM_Product> T_QCRM_Product { get; set; }
        public DbSet<T_QCRM_ProductItem> T_QCRM_ProductItem { get; set; }
        public DbSet<T_QCRM_QuickSreach> T_QCRM_QuickSreach { get; set; }
        public DbSet<T_QCRM_QuickSreachUser> T_QCRM_QuickSreachUser { get; set; }
        public DbSet<T_QCRM_Tabs> T_QCRM_Tabs { get; set; }
        public DbSet<T_QCRM_UserInForm> T_QCRM_UserInForm { get; set; }
        public DbSet<T_QCRM_UserQueryListSetting> T_QCRM_UserQueryListSetting { get; set; }
        public DbSet<T_QCRM_UserQuerySetting> T_QCRM_UserQuerySetting { get; set; }
        public DbSet<T_QWF_Config> T_QWF_Config { get; set; }
        public DbSet<T_QWF_LoginLog> T_QWF_LoginLog { get; set; }
        public DbSet<T_QWF_Menu> T_QWF_Menu { get; set; }
        public DbSet<T_QWF_MenuInUrl> T_QWF_MenuInUrl { get; set; }
        public DbSet<T_QWF_Org> T_QWF_Org { get; set; }
        public DbSet<T_QWF_Resource> T_QWF_Resource { get; set; }
        public DbSet<T_QWF_Role> T_QWF_Role { get; set; }
        public DbSet<T_QWF_RoleGroup> T_QWF_RoleGroup { get; set; }
        public DbSet<T_QWF_RoleInMenu> T_QWF_RoleInMenu { get; set; }
        public DbSet<T_QWF_RoleInResource> T_QWF_RoleInResource { get; set; }
        public DbSet<T_QWF_Seq> T_QWF_Seq { get; set; }
        public DbSet<T_QWF_User> T_QWF_User { get; set; }
        public DbSet<T_QWF_UserActionLog> T_QWF_UserActionLog { get; set; }
        public DbSet<T_QWF_UserInRole> T_QWF_UserInRole { get; set; }
        public DbSet<vw_UserInRoles> vw_UserInRoles { get; set; }
        public DbSet<T_QCRM_FormInput> T_QCRM_FormInput { get; set; }
        public DbSet<T_QCRM_Tables> T_QCRM_Tables { get; set; }
        public DbSet<T_QCRM_ListType> T_QCRM_ListType { get; set; }
        public DbSet<T_QCRM_Fields> T_QCRM_Fields { get; set; }
        public DbSet<T_QCRM_Dictionary> T_QCRM_Dictionary { get; set; }
        public DbSet<T_QCRM_UserCenter> T_QCRM_UserCenter { get; set; }
        public DbSet<T_QCRM_Form> T_QCRM_Form { get; set; }
        public DbSet<T_QCRM_RoleInQueryCategory> T_QCRM_RoleInQueryCategory { get; set; }
        public DbSet<T_QCRM_QueryList> T_QCRM_QueryList { get; set; }
        public DbSet<T_QCRM_QueryCategory> T_QCRM_QueryCategory { get; set; }
        public DbSet<T_QCRM_QueryWhere> T_QCRM_QueryWhere { get; set; }
    }
}
