//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QCRM_FormInput
    {
        public int Id { get; set; }
        public string FormCode { get; set; }
        public string TableCode { get; set; }
        public string FieldCode { get; set; }
        public string Name { get; set; }
        public string InputName { get; set; }
        public string InputType { get; set; }
        public string DefaultValueType { get; set; }
        public string DefaultValue { get; set; }
        public int SortId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string DictionaryCode { get; set; }
        public string SelectItemValue { get; set; }
        public int CssWidth { get; set; }
        public int CssHeight { get; set; }
        public string InputDesc { get; set; }
    }
}
