//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QCRM_Tabs
    {
        public int Id { get; set; }
        public string TabCode { get; set; }
        public string TableCode { get; set; }
        public string FieldCode { get; set; }
        public Nullable<int> SortId { get; set; }
    }
}
