//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QCRM_Form
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string MainTable { get; set; }
        public string ActionType { get; set; }
        public string ActionName { get; set; }
        public int ActionStyle { get; set; }
        public int StyleColums { get; set; }
        public string Remarks { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public int WindowsWidth { get; set; }
        public string ButtonStyle { get; set; }
        public string ButtonIcon { get; set; }
        public string PlugInClass { get; set; }
    }
}
