//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QCRM_QueryWhere
    {
        public int Id { get; set; }
        public int QueryCategoryId { get; set; }
        public string FieldCode { get; set; }
        public string Expression { get; set; }
        public string FieldValue { get; set; }
        public string FieldValueType { get; set; }
        public string StaticDateValue { get; set; }
        public Nullable<int> DateNum { get; set; }
        public Nullable<int> DateType { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string FieldQueryType { get; set; }
        public Nullable<int> UserCodeType { get; set; }
        public string UserCode { get; set; }
        public int SortId { get; set; }
    }
}
