//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QCRM_QueryList
    {
        public int Id { get; set; }
        public string ListType { get; set; }
        public string TableCode { get; set; }
        public string FieldCode { get; set; }
        public int StyleWidth { get; set; }
        public int SortId { get; set; }
        public string StyleCss { get; set; }
        public string TitleName { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string FieldFormatter { get; set; }
        public string FormatterType { get; set; }
        public string FieldType { get; set; }
        public int Checkbox { get; set; }
        public int Hide { get; set; }
        public int Sortable { get; set; }
        public int IsUserField { get; set; }
    }
}
