//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QCRM_ListType
    {
        public string ListType { get; set; }
        public string TypeName { get; set; }
        public int IsHide { get; set; }
        public string Remarks { get; set; }
        public string TableRelation { get; set; }
        public string OrderBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public int PageSize { get; set; }
        public string AscOrDesc { get; set; }
    }
}
