//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QCRM_Fields
    {
        public string Code { get; set; }
        public string TableCode { get; set; }
        public string Name { get; set; }
        public string FieldType { get; set; }
        public int FieldTypeLength { get; set; }
        public int Deleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string Remarks { get; set; }
        public int PK { get; set; }
        public int IsNotNull { get; set; }
        public int OnlyKey { get; set; }
        public int IsVirtual { get; set; }
    }
}
