//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QCRM_Dictionary
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public int ParentId { get; set; }
        public string ItemName { get; set; }
        public int ItemValueType { get; set; }
        public string ItemValue { get; set; }
        public int ItemSort { get; set; }
        public int Hide { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string IdList { get; set; }
        public int IsSubNode { get; set; }
        public int LayerId { get; set; }
        public int DictionaryType { get; set; }
        public string Remarks { get; set; }
        public string ViewName { get; set; }
        public int DataSource { get; set; }
        public string ItemFullNamePath { get; set; }
    }
}
