//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QWF_Config
    {
        public int ConfigId { get; set; }
        public string ConfigResourceCode { get; set; }
        public string ConfigName { get; set; }
        public string ConfigValueType { get; set; }
        public string ConfigValue { get; set; }
        public int ParentId { get; set; }
        public int LayerId { get; set; }
        public string ConfigIdList { get; set; }
        public int SortId { get; set; }
        public int IsDelete { get; set; }
        public int IsHidden { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public int IsSubNode { get; set; }
        public string ConfigRemarks { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
    }
}
