//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QWF_Seq
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Prefix { get; set; }
        public string DateFormart { get; set; }
        public int SerialLength { get; set; }
        public int CurrentNumber { get; set; }
    }
}
