//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QWF_User
    {
        public int UserId { get; set; }
        public string UserCode { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public int OrgId { get; set; }
        public int Leader { get; set; }
        public string LastLoginIp { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public int UserStatus { get; set; }
        public int IsDelete { get; set; }
        public string QQ { get; set; }
        public string Realname { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Weixin { get; set; }
        public string Fax { get; set; }
        public string UserRemarks { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
    }
}
