//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QWF.CRM.DbAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserInRoles
    {
        public int UserId { get; set; }
        public string RoleIds { get; set; }
        public string RoleCodes { get; set; }
        public string RoleNames { get; set; }
    }
}
